config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "counts#index"
  resources :counts
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id:1, name: '--'},
    {id:2, name: '経済'},
    {id:3, name: '地域'},
    {id:4, name: 'エンタメ'},
    {id:5, name: 'グルメ'}
  ]

  include ActiveHash::Associations
  has_many :counts
end

app/models/count.rb
class Count < ApplicationRecord
  # validation
  with_options presence: true do
    validates :name
    validates :category
    validates :release
    validates :image
  end    
  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :release_id
  end
  # Association
  has_many :details, dependent: :destroy
  accepts_nested_attributes_for :details, allow_destroy: true
  belongs_to :user 
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :release
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :count
end

app/models/release.rb
class Release < ActiveHash::Base
  self.data = [
    { id:1, name: '--' },
    { id:2, name: '公開' },
    { id:3, name: '非公開' }
  ]

  include ActiveHash::Associations
  has_many :counts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true
  has_many :counts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configiure_permitted_parameters, if: :devise_controller?

  private
  def configiure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_count, only: [:show, :edit, :update, :destroy]
  before_action :private_to_index, only: [:show]
  before_action :move_to_index, only: [:edit, :destroy]
  
  def index
    @counts = Count.includes(:user).order("created_at")
  end

  def new
    @count = Count.new
    @count.details.build
  end

  def create
    @count = Count.new(count_params)
    if @count.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @count.update(count_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @count.destroy
    redirect_to root_path
  end

  private
  def count_params
    params.require(:count).permit(:image, :name, :remark, :category_id, :release_id, :trials,details_attributes: [:id, :count_id, :title, :number, :probability, :_destroy]).merge(user_id: current_user.id)
  end

  def find_count
    @count = Count.find(params[:id])
    @details = @count.details.includes(:count)
  end

  def private_to_index
    if user_signed_in? && current_user.id != @count.user && @count.release_id == 3
      redirect_to root_path
    end
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @count.user.id
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @counts = @user.counts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/counts/_count-show.html.erb
<tr>
  <th class="detail-item">タイトル</th>
  <td class="detail-value"><%= detail.title %></td>
</tr>
<tr>
  <th class="detail-item">回数</th>
  <td class="detail-value"><%= detail.number %></td>
</tr>
<tr>
  <th class="detail-item">確率</th>
  <td class="detail-value"><%= detail.probability %></td>
</tr>

app/views/counts/_count.html.erb
<% if count.release_id == 2 %>
  <div class="card">
    <%= link_to image_tag(count.image, class: :card__img ), count_path(count.id) %>
    <div class="card__body">
      <%= link_to count.name, count_path(count.id), class: :card__title%>
      <%= link_to "by#{count.user.nickname}", root_path, class: :card__user %>
    </div>
  </div>
<% else %>
<% end %>

app/views/counts/edit.html.erb
<div class="counts-main">
  <h2 class="counts-title">集計情報の入力</h2>
  <%= nested_form_for(@count) do |f| %>
  
  <%# カウントのサムネ（任意） %>
  <div class="image-upload">
    <div class="weight-bold-text">
      サムネイル
      <span class="indispenable">必須</span>
    </div>
  </div>
  <div class="click-upload">
    <p>
      クリックしてファイルをアップロード
    </p>
    <%= f.file_field :image, id:"count-image" %>
  </div>

  <%# 集計の名前と概要 %>
  <div class="new-counts">
    <div class="weight-bold-text">
      集計名
      <span class="indispenable">必須</span>
    </div>
    <%= f.text_area :name, class:"counts-text", id:"count-name" %>
    <div class="counts-explain">
      <div class="weight-bold-text">
        集計の概要
        <span class="any">任意</span>
      </div>
      <%= f.text_area :remark, class:"counts-text", id:"count-info" %>
    </div>
    <%# カテゴリーの設定 %>
    <div class="count-detail">
      <div class="weight-bold-text">
        カテゴリー
        <span class="indispenable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"count-category"})%>
    </div>
    <%# 公開・非公開の設定 %>
    <div class="count-detail">
      <div class="weight-bold-text">
        公開・非公開
        <span class="indispenable">必須</span>
      </div>
      <%= f.collection_select(:release_id, Release.all, :id, :name, {}, {class:"select-box", id:"count-release"})%>
    </div>
  </div>

  <%# 動的フォームの作成 %>
  <div class="detail_form">
    <%= f.fields_for :details do |detail| %>
      <div class="detail-form">
        <div class="detail-bold-text">
          タイトル
        </div>
        <%= detail.text_field :title, class:"detail-title" %>
      </div>

      <div class="detail-form">
        <div class="detail-bold-text">
          回数
        </div>
        <%= detail.text_field :number, class:"detail-number" %>
        <%= button_tag "up",type:'button',class:"count-up-btn" %>
        <%= button_tag "down",type:'button',class:"count-down-btn" %>
      </div>

      <div class="detail-form">
        <div class="detail-bold-text">
          確率
        </div>
        <%= detail.text_field :probability, class:"detail-probability" %>
        <%= button_tag "calc.",type:'button',class:"count-calc-btn" %>
      </div>
      <%= f.link_to_remove "削除" %>
    <% end %>
    <%= f.link_to_add "追加", :details %>
    <%= button_tag "set", type:'button', class:"set-btn", id:"set-id"%>
  </div>

  <%# 試行回数 %>
  <div class="trial-form">
    <div class="trial-bold-text">
        試行回数
    </div>
    <div class = "trial-input">
      <%= f.text_field :trials, class:"trial-number", id:"trials" %>
      <%= button_tag "up",type:'button',class:"count-btn",id:"trial-up-btn" %>
      <%= button_tag "down",type:'button',class:"count-btn",id:"trial-down-btn" %>
    </div>
  </div>

  <%# 送信ボタン %>
  <div class="count-btn-contents">
    <%= f.submit "投稿" ,class:"submit-btn" %>
    <%= link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>
</div>

app/views/counts/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "マイページへ", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'count', collection: @counts %>
    </div>
  </div>
</main>

app/views/counts/new.html.erb
<div class="counts-main">
  <h2 class="counts-title">集計情報の入力</h2>
  <%= nested_form_for(@count) do |f| %>
  
  <%# カウントのサムネ（任意） %>
  <div class="image-upload">
    <div class="weight-bold-text">
      サムネイル
      <span class="indispenable">必須</span>
    </div>
  </div>
  <div class="click-upload">
    <p>
      クリックしてファイルをアップロード
    </p>
    <%= f.file_field :image, id:"count-image" %>
  </div>

  <%# 集計の名前と概要 %>
  <div class="new-counts">
    <div class="weight-bold-text">
      集計名
      <span class="indispenable">必須</span>
    </div>
    <%= f.text_area :name, class:"counts-text", id:"count-name" %>
    <div class="counts-explain">
      <div class="weight-bold-text">
        集計の概要
        <span class="any">任意</span>
      </div>
      <%= f.text_area :remark, class:"counts-text", id:"count-info" %>
    </div>
    <%# カテゴリーの設定 %>
    <div class="count-detail">
      <div class="weight-bold-text">
        カテゴリー
        <span class="indispenable">必須</span>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"count-category"})%>
    </div>
    <%# 公開・非公開の設定 %>
    <div class="count-detail">
      <div class="weight-bold-text">
        公開・非公開
        <span class="indispenable">必須</span>
      </div>
      <%= f.collection_select(:release_id, Release.all, :id, :name, {}, {class:"select-box", id:"count-release"})%>
    </div>
  </div>

  <%# 動的フォームの作成 %>
  <div class="detail_form">
    <%= f.fields_for :details do |detail| %>
      <div class="detail-form">
        <div class="detail-bold-text">
          タイトル
        </div>
        <%= detail.text_field :title, class:"detail-title" %>
      </div>

      <div class="detail-form">
        <div class="detail-bold-text">
          回数
        </div>
        <%= detail.text_field :number, class:"detail-number" %>
        <%= button_tag "up",type:'button',class:"count-up-btn" %>
        <%= button_tag "down",type:'button',class:"count-down-btn" %>
      </div>

      <div class="detail-form">
        <div class="detail-bold-text">
          確率
        </div>
        <%= detail.text_field :probability, class:"detail-probability" %>
        <%= button_tag "calc.",type:'button',class:"count-calc-btn" %>
      </div>
      <%= f.link_to_remove "削除" %>
    <% end %>
    <%= f.link_to_add "追加", :details %>
    <%= button_tag "set", type:'button', class:"set-btn", id:"set-id"%>
  </div>

  <%# 試行回数 %>
  <div class="trial-form">
    <div class="trial-bold-text">
        試行回数
    </div>
    <div class = "trial-input">
      <%= f.text_field :trials, class:"trial-number", id:"trials" %>
      <%= button_tag "up",type:'button',class:"count-btn",id:"trial-up-btn" %>
      <%= button_tag "down",type:'button',class:"count-btn",id:"trial-down-btn" %>
    </div>
  </div>

  <%# 送信ボタン %>
  <div class="count-btn-contents">
    <%= f.submit "投稿" ,class:"submit-btn" %>
    <%= link_to 'もどる', root_path, class:"back-btn" %>
  </div>
  <% end %>
</div>

app/views/counts/show.html.erb
<div class="item-box">
  <h2 class="name">
    <%= @count.name %>
  </h2>
  <div class='item-img-content'>
    <%= image_tag @count.image ,class:"item-box-img" %>
  </div>
  <% if user_signed_in? && @count.user.id == current_user.id  %>
    <%= link_to '編集', edit_count_path(@count.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', count_path(@count.id), method: :delete, class:'item-destroy' %>
  <% end %>

  <div class="item-explain-box">
    <span><%= @count.remark %></span>
  </div>
  <table class="detail-table">
    <tbody>
      <tr>
        <th class="detail-item">投稿者</th>
        <td class="detail-value"><%= @count.user.nickname %></td>
      </tr>
      <tr>
        <th class="detail-item">カテゴリー</th>
        <td class="detail-value"><%= @count.category.name %></td>
      </tr>
      <tr>
        <th class="detail-item">試行回数</th>
        <td class="detail-value"><%= @count.trials %></td>
      </tr>
      <% if @details %>
          <%= render partial: 'count-show', collection: @details, as: :detail %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Count30866</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "Count.APP", root_path, class: :nav__link %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Count", new_count_path, class: :nav__btn %>
            </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Count.APP All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/_user_show.html.erb
<div class="card">
    <%= link_to image_tag(count.image, class: :card__img ), count_path(count.id) %>
    <div class="card__body">
      <%= link_to count.name, count_path(count.id), class: :card__title%>
      <%= link_to "by#{count.user.nickname}", user_path(count.user.id), class: :card__user %>
    </div>
</div>

app/views/users/_user_show_count.html.erb
<% if count.release_id == 2 %>
  <div class="card">
    <%= link_to image_tag(count.image, class: :card__img ), count_path(count.id) %>
    <div class="card__body">
      <%= link_to count.name, count_path(count.id), class: :card__title%>
      <%= link_to "by#{count.user.nickname}", user_path(count.user.id), class: :card__user %>
    </div>
  </div>
<% else %>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿"%>
      </h2>
      <div class="user__card">
        <%# 投稿者本人がユーザーマイページへ移動した場合 %>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= render partial: 'user_show', collection: @counts, as: :count %>
        <% else %>
        <%# 本人以外がユーザーマイページに移動した場合は非公開が見えないようにする%>
          <%= render partial: 'user_show_count', collection: @counts, as: :count %>
        <% end %>
      </div>
    </div>
  </div>
</div>